site_name: BeepyRC/Wiki
repo_name: BeepyRC
site_description: >-
  Using old RC components to create a smart RC vehicle.
copyright: Copyright © 2025 David Arnaiz
theme:
  name: material
  language: en
  logo: imgs/test_icon.png
  favicon: imgs/test_icon.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.sections

  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-3
        name: Switch to light mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

plugins:
    - search:
    - mkdoxy:
        projects:
          template:
            src-dirs: firmware
            full-doc: True
            doxy-cfg:
              FILE_PATTERNS: "*.c *.h*"
              RECURSIVE: True
              EXCLUDE_PATTERNS: "*/docs/* */firmware/make/build/* */external_libs/* */firmware/make/bin/*"
              EXTRACT_STATIC: "YES"

nav:
    - Home: README.md
    - Getting Started:
        - getting_started/setup.md
        - getting_started/hardware.md
    - Notes:
        - notes/motor_driver.md
        - notes/sbus.md
    - About:
        - about/credits.md
    - Source:
        - Files: template/files.md
        - Groups:
            - Libs: template/group__Libs.md
            - Targets: template/group__Target.md
            - Ports: template/group__Port.md
            - App: template/group__App.md
        - App Modules:
            - RC: template/group__Rc.md
            - Controller: template/group__Controller.md
            - Supervisor: template/group__Supervisor.md
            - BSP: template/group__Bsp.md
            - Main: template/group__Main.md
        - Platform:
            - Utils: template/group__PltUtils.md
            - Types: template/group__PltTypes.md
            - Assert: template/group__PltAssert.md
            - Defines: template/group__PltDefines.md
            - Memory: template/group__PltMem.md

